name: Vault Dotnet Examples Tests
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    env:
      VAULT_ADDR: http://127.0.0.1:8200
      VAULT_DEV_ROOT_TOKEN_ID: testtoken
      VAULT_TOKEN: testtoken
      EXPECTED_SECRET_VALUE: Hashi123
    strategy:
      matrix:
        dotnet-version: ['3.1.x']
    steps:
      - uses: actions/checkout@v2
      
      - name: Run docker-compose
        run: docker-compose up -d vault

      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Set up environment
        run: |
          ./setup.sh
          echo "APPROLE_ROLE_ID=$(curl -H "X-Vault-Token: ${VAULT_DEV_ROOT_TOKEN_ID}" ${VAULT_ADDR}/v1/auth/approle/role/my-role/role-id | jq -r .data.role_id)" >> $GITHUB_ENV

      - name: Build Tests
        run: |
          cd dotnet/ExampleTests
          dotnet restore
          dotnet build

      - name: Run Tests
        run: |
          cd dotnet/ExampleTests
          TOKEN=${VAULT_DEV_ROOT_TOKEN_ID} dotnet test
